"""add operation_number brand model plate quantity officers

Revision ID: ee8a5da7dc44
Revises: 1ec9fe7d9562
Create Date: 2026-06-21 19:48:48.478540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8a5da7dc44'
down_revision = '1ec9fe7d9562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigation_equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_number', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['operation_number'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('officers', sa.Text(), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('plate', sa.String(length=10), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('plate')
        batch_op.drop_column('model')
        batch_op.drop_column('brand')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('officers')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('operation_number')

    with op.batch_alter_table('investigation_equipments', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
